### ISSUE TITLE
Request: Tor: The Onion Router Option

### ISSUE THREAD

**Issue by Rbagman** [JonasCz/save-for-offline#30]
Being able to save over Tor would be excellent, because this app disables scripts. A feature sorely lacking --- none claim to disable scripts --- in the available Firefox MHT (MHTML) addons.

**Comment by JonasCz** [comment]
I'll take a look. 

However if you install tor (orbot app) on your device, it should already transparently send all traffic through tor, without me making any changes, right ?

**Comment by Rbagman** [comment]
Thanks.

Actually, that's orWall and I dismissed it because it's. Not a true firewall and I conflicts with AFWall (their F-Froid description, but I will take a closer look at orWall.

-----Original Message-----

**Comment by Rbagman** [comment]
I just realize what you were talking about --- I did not notice this Orbot option before. Thanks.
I'll have to hit the forum.

-----Original Message-----

**Comment by JonasCz** [comment]
Yes, I think it should be possible to do this using an external app, without me changing anything (Which I'm not sure is really a good idea, since other people seem to really like the fact that this app is small and light, and I'd like to keep it that way, without any bulky additions) 

Let me know if you find a way to do what you want, and if not, I'd see what I can do to make my app work well with Tor.

**Comment by JonasCz** [comment]
Closing this issue since I probably won't be able to do this.

You can use an external app to rout traffic through Tor, but I won't add anything to the app itself, since that will be quite difficult and also make the app bigger if I include Tor and all the bits and pieces it requires
